
# Set Up our application's listening PORT
server:
  port: 8900

# Application Name
spring:
  application:
    name: image-service

  # H2 Database Property
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true

  # Setting up Multipart Max Requirments
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB


